[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[phases.install]
cmds = [
  "pip install numpy pandas",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"