[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m venv .venv",
  ".venv/bin/python -m pip install --upgrade pip",
  ".venv/bin/python -m pip install numpy pandas"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"